[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "api"
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client"]
  included_files = ["prisma/**", "node_modules/.prisma/**"]

[dev]
framework = "#custom"
command = "npm run dev:web"
targetPort = 5173
port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
